name: trackwise
description: A new Flutter project.

publish_to: "none" # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # SDK constraint

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib\assets\facebook_icon.png
    - lib\assets\google_icon.png
