name: trackwise
description: A new Flutter project.

publish_to: "none" # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # SDK constraint

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.3.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  firebase_data_connect: ^0.1.2+4
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/facebook_icon.png
    - lib/assets/google_icon.png
